version: 2
sources:
  - name: sap_adw
    description: Fonte do SAP da Adventure Works
    schema: sap_adw
    tables:
      - name: creditcard
        description: Tabela de Cartões de crédito
        columns:
          - name: creditcardid
            description: ID do cartão deve ser único e não nulo.
            tests:
              - unique
              - not_null
      - name: personcreditcard
        description: Tabela de Cartões de crédito + Pessoa
        columns:
          - name: businessentityid
            description: ID da pessoa deve ser único e não nulo.
            tests:
              - unique
              - not_null
          - name: creditcardid
            description: ID do cartão deve ser único e não nulo.
            tests:
              - unique
              - not_null     
      - name: customer
        description: Tabela de clientes da AW
        columns:
          - name: customerid
            description: ID do cliente deve ser único e não nulo. Quando o ID da pessoa é nulo, o ID da loja não é e vice-versa.
            tests:
              - unique
              - not_null
      - name: person
        description: Tabela de pessoas clientes da AW
        columns:
          - name: businessentityid
            description: ID da pessoa deve ser único e não nulo.
            tests:
              - unique
              - not_null
      - name: store
        description: Tabela de lojas clientes da AW
        columns:
          - name: businessentityid
            description: ID da loja deve ser único e não nulo.
            tests:
              - unique
              - not_null
      - name: address
        description: Tabela de endereços de pessoas clientes da AW
        columns:
          - name: addressid
            description: ID do endereço deve ser único e não nulo.
            tests:
              - unique
              - not_null
      - name: stateprovince
        description: Tabela de estados dos enderecos de pessoas clientes da AW
        columns:
          - name: stateprovinceid
            description: ID do estado deve ser único e não nulo.
            tests:
              - unique
              - not_null
      - name: countryregion
        description: Tabela de países dos enderecos de pessoas clientes da AW
        columns:
          - name: countryregioncode
            description: ID do país deve ser único e não nulo.
            tests:
              - unique
              - not_null
      - name: product
        description: Tabela de Produtos vendidos pela AW
        columns:
          - name: productid
            description: ID do produto deve ser único e não nulo.
            tests:
              - unique
              - not_null
      - name: salesorderheader
        description: Tabela de Vendas da AW. Cada linha é uma venda distinta.
        columns:
          - name: salesorderid
            description: ID da venda deve ser único e não nulo.
            tests:
              - unique
              - not_null
      - name: salesorderdetail
        description: Tabela de Vendas da AW. Cada venda pode aparecer mais de uma vez. A pk é salesorderdetail, que se refere a uma venda-produto.
        columns:
          - name: salesorderdetailid
            description: ID da venda-produto deve ser único e não nulo.
            tests:
              - unique
              - not_null
      - name: salesreason
        description: Tabela de Motivos de Vendas da AW.
        columns:
          - name: salesreasonid
            description: ID da venda-produto deve ser único e não nulo.
            tests:
              - unique
              - not_null
      - name: salesorderheadersalesreason
        description: Tabela de Motivos de Vendas da AW.
        columns:
        - name: salesorderid
          description: ID da venda-produto deve ser não nulo. Não tem como ser único dado que cada venda pode ter mais de 1 motivo.
          tests:
            - not_null